[server]
headless = true
port = 8501

[theme]
base = "light"
primaryColor = "#009de2"
backgroundColor = "#F0F4F8"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1E293B"
font = "sans serif"

[browser]
gatherUsageStats = false
